#!/bin/bash
#
# Plugin for analyzing the postfix deferred queue
# print out 5 top deferred outgoing mails according to their full recipient, recipient provider and sender
#
# Maintainer: t.wurzbacher@mail.de
#

DIRECTORY=/var/spool/postfix/deferred/

if [ -d "$DIRECTORY" ]; then
  echo "<<<deferred_mail>>>"
  
  echo "[addresses]"
  find $DIRECTORY -type f -print0 | xargs -0  /usr/sbin/postcat -e | grep original_recipient | egrep -o '[a-zA-Z0-9]+@.+' |sort | uniq -c | sort -nr | head -5

  echo "[provider]"
  find $DIRECTORY -type f -print0 | xargs -0  /usr/sbin/postcat -e | grep original_recipient | egrep -o '@.+' | sort | uniq -c | sort -nr | head -5

  echo "[sender]"
  find $DIRECTORY -type f -print0 | xargs -0  /usr/sbin/postcat -e | grep sender | egrep -o '[a-zA-Z0-9]+@.+' | sort | uniq -c | sort -nr | head -5
fi
