#!/bin/bash
#
# Verifies the configured DKIM Keys against the public ones in DNS records.
# The test will read in all keys from KeyTable and check them against the default config.
# It monitores if the private key and the public DKIM key retrieved match.
#
# For use in checkmk you need to add the plugin evaluation to checkmk server:
# https://github.com/tobiWu/monitoring/blob/master/check_mk/plugin_evaluation/opendkim
#
# written by Tobias Wurzbacher <tobias.wurzbacher@elster.de> at 2018-03-13
# update by Tobias Wurzbacher <tobias.wurzbacher@elster.de> at 2019-07-18
#   don't care about configfiles
#   get all used keys from config - Test

# set path to list of domainkeys
TABLE='/etc/opendkim/KeyTable'

if [ -f $TABLE ]; then

        KEYS=$(grep "domainkey" /etc/opendkim/KeyTable)

        echo $KEYS | while read KEY
        do
            SELECTOR=$(echo $KEY | cut -d'.' -f1)
            DOMAIN=$(echo $KEY | cut -d'/' -f5)

            if [ -n "$SELECTOR" ]; then
                echo "<<<opendkim>>>"
                ANSWER=$(opendkim-testkey -d $DOMAIN -s $SELECTOR -vvv 2>&1)
                echo $ANSWER
            fi
        done

else
        exit 0
fi

